// Derived from the Natural Earth 110m GeoJSON by shared border segments.
// This is a clean fallback adjacency map and can be regenerated if the source geo data changes.

export const COUNTRY_NEIGHBOR_CODES: Readonly<Record<string, readonly string[]>> = {
  "AE": ["OM", "SA"],
  "AF": ["CN", "IR", "PK", "TJ", "TM", "UZ"],
  "AL": ["GR", "ME", "MK", "XK"],
  "AM": ["AZ", "GE", "IR", "TR"],
  "AO": ["CD", "CG", "NA", "ZM"],
  "AR": ["BO", "BR", "CL", "PY", "UY"],
  "AT": ["CH", "CZ", "DE", "HU", "IT", "SI", "SK"],
  "AZ": ["AM", "GE", "IR", "RU"],
  "BA": ["HR", "ME", "RS"],
  "BD": ["IN", "MM"],
  "BE": ["DE", "FR", "LU", "NL"],
  "BF": ["BJ", "CI", "GH", "ML", "NE", "TG"],
  "BG": ["GR", "MK", "RO", "RS", "TR"],
  "BI": ["CD", "RW", "TZ"],
  "BJ": ["BF", "NE", "NG", "TG"],
  "BN": ["MY"],
  "BO": ["AR", "BR", "CL", "PE", "PY"],
  "BR": ["AR", "BO", "CO", "FR", "GY", "PE", "PY", "SR", "UY", "VE"],
  "BT": ["CN", "IN"],
  "BW": ["NA", "ZA", "ZM", "ZW"],
  "BY": ["LT", "LV", "PL", "RU", "UA"],
  "BZ": ["GT", "MX"],
  "CA": ["US"],
  "CD": ["AO", "BI", "CF", "CG", "RW", "SS", "TZ", "UG", "ZM"],
  "CF": ["CD", "CG", "CM", "SD", "SS", "TD"],
  "CG": ["AO", "CD", "CF", "CM", "GA"],
  "CH": ["AT", "DE", "FR", "IT"],
  "CI": ["BF", "GH", "GN", "LR", "ML"],
  "CL": ["AR", "BO", "PE"],
  "CM": ["CF", "CG", "GA", "GQ", "NE", "NG", "TD"],
  "CN": ["AF", "BT", "IN", "KG", "KP", "KZ", "LA", "MM", "MN", "NP", "PK", "RU", "TJ", "VN"],
  "CO": ["BR", "EC", "PA", "PE", "VE"],
  "CR": ["NI", "PA"],
  "CZ": ["AT", "DE", "PL", "SK"],
  "DE": ["AT", "BE", "CH", "CZ", "DK", "FR", "LU", "NL", "PL"],
  "DJ": ["ER", "ET"],
  "DK": ["DE"],
  "DO": ["HT"],
  "DZ": ["LY", "MA", "ML", "MR", "NE", "TN"],
  "EC": ["CO", "PE"],
  "EE": ["LV", "RU"],
  "EG": ["IL", "LY", "SD"],
  "ER": ["DJ", "ET", "SD"],
  "ES": ["FR", "PT"],
  "ET": ["DJ", "ER", "KE", "SD", "SO", "SS"],
  "FI": ["NO", "RU", "SE"],
  "FR": ["BE", "BR", "CH", "DE", "ES", "IT", "LU", "SR"],
  "GA": ["CG", "CM", "GQ"],
  "GB": ["IE"],
  "GE": ["AM", "AZ", "RU", "TR"],
  "GH": ["BF", "CI", "TG"],
  "GM": ["SN"],
  "GN": ["CI", "GW", "LR", "ML", "SL", "SN"],
  "GQ": ["CM", "GA"],
  "GR": ["AL", "BG", "MK", "TR"],
  "GT": ["BZ", "HN", "MX", "SV"],
  "GW": ["GN", "SN"],
  "GY": ["BR", "SR", "VE"],
  "HN": ["GT", "NI", "SV"],
  "HR": ["BA", "HU", "ME", "RS", "SI"],
  "HT": ["DO"],
  "HU": ["AT", "HR", "RO", "RS", "SI", "SK", "UA"],
  "ID": ["MY", "PG", "TL"],
  "IE": ["GB"],
  "IL": ["EG", "JO", "LB", "SY"],
  "IN": ["BD", "BT", "CN", "MM", "NP", "PK"],
  "IQ": ["IR", "JO", "KW", "SA", "SY", "TR"],
  "IR": ["AF", "AM", "AZ", "IQ", "PK", "TM", "TR"],
  "IT": ["AT", "CH", "FR", "SI"],
  "JO": ["IL", "IQ", "SA", "SY"],
  "KE": ["ET", "SO", "SS", "TZ", "UG"],
  "KG": ["CN", "KZ", "TJ", "UZ"],
  "KH": ["LA", "TH", "VN"],
  "KP": ["CN", "KR", "RU"],
  "KR": ["KP"],
  "KW": ["IQ", "SA"],
  "KZ": ["CN", "KG", "RU", "TM", "UZ"],
  "LA": ["CN", "KH", "MM", "TH", "VN"],
  "LB": ["IL", "SY"],
  "LR": ["CI", "GN", "SL"],
  "LS": ["ZA"],
  "LT": ["BY", "LV", "PL", "RU"],
  "LU": ["BE", "DE", "FR"],
  "LV": ["BY", "EE", "LT", "RU"],
  "LY": ["DZ", "EG", "NE", "SD", "TD", "TN"],
  "MA": ["DZ"],
  "MD": ["RO", "UA"],
  "ME": ["AL", "BA", "HR", "RS", "XK"],
  "MK": ["AL", "BG", "GR", "RS", "XK"],
  "ML": ["BF", "CI", "DZ", "GN", "MR", "NE", "SN"],
  "MM": ["BD", "CN", "IN", "LA", "TH"],
  "MN": ["CN", "RU"],
  "MR": ["DZ", "ML", "SN"],
  "MW": ["MZ", "TZ", "ZM"],
  "MX": ["BZ", "GT", "US"],
  "MY": ["BN", "ID", "TH"],
  "MZ": ["MW", "SZ", "TZ", "ZA", "ZM", "ZW"],
  "NA": ["AO", "BW", "ZA", "ZM"],
  "NE": ["BF", "BJ", "CM", "DZ", "LY", "ML", "NG", "TD"],
  "NG": ["BJ", "CM", "NE"],
  "NI": ["CR", "HN"],
  "NL": ["BE", "DE"],
  "NO": ["FI", "RU", "SE"],
  "NP": ["CN", "IN"],
  "OM": ["AE", "SA", "YE"],
  "PA": ["CO", "CR"],
  "PE": ["BO", "BR", "CL", "CO", "EC"],
  "PG": ["ID"],
  "PK": ["AF", "CN", "IN", "IR"],
  "PL": ["BY", "CZ", "DE", "LT", "RU", "SK", "UA"],
  "PT": ["ES"],
  "PY": ["AR", "BO", "BR"],
  "QA": ["SA"],
  "RO": ["BG", "HU", "MD", "RS", "UA"],
  "RS": ["BA", "BG", "HR", "HU", "ME", "MK", "RO", "XK"],
  "RU": ["AZ", "BY", "CN", "EE", "FI", "GE", "KP", "KZ", "LT", "LV", "MN", "NO", "PL", "UA"],
  "RW": ["BI", "CD", "TZ", "UG"],
  "SA": ["AE", "IQ", "JO", "KW", "OM", "QA", "YE"],
  "SD": ["CF", "EG", "ER", "ET", "LY", "SS", "TD"],
  "SE": ["FI", "NO"],
  "SI": ["AT", "HR", "HU", "IT"],
  "SK": ["AT", "CZ", "HU", "PL", "UA"],
  "SL": ["GN", "LR"],
  "SN": ["GM", "GN", "GW", "ML", "MR"],
  "SO": ["ET", "KE"],
  "SR": ["BR", "FR", "GY"],
  "SS": ["CD", "CF", "ET", "KE", "SD", "UG"],
  "SV": ["GT", "HN"],
  "SY": ["IL", "IQ", "JO", "LB", "TR"],
  "SZ": ["MZ", "ZA"],
  "TD": ["CF", "CM", "LY", "NE", "SD"],
  "TG": ["BF", "BJ", "GH"],
  "TH": ["KH", "LA", "MM", "MY"],
  "TJ": ["AF", "CN", "KG", "UZ"],
  "TL": ["ID"],
  "TM": ["AF", "IR", "KZ", "UZ"],
  "TN": ["DZ", "LY"],
  "TR": ["AM", "BG", "GE", "GR", "IQ", "IR", "SY"],
  "TZ": ["BI", "CD", "KE", "MW", "MZ", "RW", "UG", "ZM"],
  "UA": ["BY", "HU", "MD", "PL", "RO", "RU", "SK"],
  "UG": ["CD", "KE", "RW", "SS", "TZ"],
  "US": ["CA", "MX"],
  "UY": ["AR", "BR"],
  "UZ": ["AF", "KG", "KZ", "TJ", "TM"],
  "VE": ["BR", "CO", "GY"],
  "VN": ["CN", "KH", "LA"],
  "XK": ["AL", "ME", "MK", "RS"],
  "YE": ["OM", "SA"],
  "ZA": ["BW", "LS", "MZ", "NA", "SZ", "ZW"],
  "ZM": ["AO", "BW", "CD", "MW", "MZ", "NA", "TZ", "ZW"],
  "ZW": ["BW", "MZ", "ZA", "ZM"],
} as const;

const MANUAL_NEIGHBOR_OVERRIDES: Readonly<Record<string, readonly string[]>> = {
  AD: ["ES", "FR"],
  LI: ["AT", "CH"],
  MC: ["FR"],
  SM: ["IT"],
  VA: ["IT"],
  PS: ["EG", "IL", "JO"],
} as const;

export function getNeighborCodes(countryCode: string): readonly string[] {
  const normalized = countryCode.trim().toUpperCase();
  const neighbors = COUNTRY_NEIGHBOR_CODES[normalized] ?? [];
  const manualNeighbors = MANUAL_NEIGHBOR_OVERRIDES[normalized] ?? [];

  return Array.from(new Set([...neighbors, ...manualNeighbors]));
}

export function isNeighboringCountryCode(
  leftCountryCode: string | null,
  rightCountryCode: string | null,
): boolean {
  if (!leftCountryCode || !rightCountryCode) {
    return false;
  }

  const left = leftCountryCode.trim().toUpperCase();
  const right = rightCountryCode.trim().toUpperCase();

  if (!left || !right || left === right) {
    return false;
  }

  return getNeighborCodes(left).includes(right);
}
